# Recall from last session

1. Declaring variables
2. For Loop
3. conditions (partially)

## Today we will see: 

# Conditions

In [4]:
x = 5 
y = 1 

if x<y: 
    print("x is less than y")
elif x==y: 
    print("x equal y")
else: 
    print("x is not less than y")

x is not less than y


In [5]:
if (x==1)and(y==1): 
    print("x and y equal 1")
elif (x==1) or (y==1): 
    print("x or y equal 1")
else: 
    print("none of the previous cdts")

x or y equal 1


# Manipulating strings

In [10]:
prenom = "Thibaut"
nom = 'Germain'
espace = " "
retour_ligne ="\n"
tabulation = "\t"

print(prenom + espace + nom )
print(prenom + retour_ligne + nom)
print(prenom + tabulation+ nom)


Thibaut Germain
Thibaut
Germain
Thibaut	Germain


In [12]:
prenom[0]

'T'

In [ ]:
lentgh = len(prenom)
prenom[lentgh]

IndexError: string index out of range

In [17]:
prenom[lentgh-1]

't'

In [19]:
prenom[-2]

'u'

In [20]:
prenom[1:4]

'hib'

In [22]:
prenom[:4]

'Thib'

In [21]:
prenom[:lentgh:2]

'Tiat'

In [27]:
file_type = ".csv"
filename = "my_data.csv"

print(f"Is {filename} a {file_type}: {file_type in filename}")

Is my_data.csv a .csv: True


In [25]:
filename.endswith(file_type)

True

In [28]:
"123" * 10

'123123123123123123123123123123'

In [29]:
"#"*1000

'#######################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################

In [31]:
prenom

'Thibaut'

In [30]:
prenom.lower()

'thibaut'

In [32]:
prenom.upper()

'THIBAUT'

# Manipulating lists

In [37]:
lst = [1,2,3,6,0]
lst_1 = [2,"a",True]

In [40]:
lst[:2] = [4,5]
lst

[4, 5, 3, 6, 0]

In [44]:
lst[::2] += [1,2,3]

ValueError: attempt to assign sequence of size 6 to extended slice of size 3

In [49]:
prenom_lst = list(prenom)
prenom_lst
"_".join(prenom_lst)

'T_h_i_b_a_u_t'

In [53]:
lst1= ["a", "A"]
lst2 = [1,2]

print(sum(lst2))
print(min(lst1))
print(max(lst1))

3
A
a


In [56]:
lst_main =[lst1, lst2]
lst_main

[['a', 'A'], [1, 2]]

In [59]:
loop_lst = [i for i in range(20) if i%2 ==0]
loop_lst

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [62]:
[elt for ls in lst_main for elt in ls]

['a', 'A', 1, 2]

In [63]:
lst1 + lst2

['a', 'A', 1, 2]

In [64]:
["a", "b"] * 4

['a', 'b', 'a', 'b', 'a', 'b', 'a', 'b']

In [ ]:
lst1 = 

TypeError: list expected at most 1 argument, got 2

# Manipulating dictionaries

In [67]:
dct = dict(
    a = 1, 
    b=2
)
dct

{'a': 1, 'b': 2}

In [69]:
dct = {
    "a" : 1, 
    "b" : 2,
}
dct

{'a': 1, 'b': 2}

In [70]:
dct["a"]

1

In [71]:
dct.keys()

dict_keys(['a', 'b'])

In [72]:
dct.values()

dict_values([1, 2])

In [74]:
for key,value in dct.items(): 
    print(f"{key}:{value}")

a:1
b:2


# Manipulating arrays

In [ ]:
import numpy as np

lst = [[1,2,3],[4,5,6],[7,8,9]]

print(lst)

M = np.array(lst)
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
print(type(lst))
print(type(M))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
np.shape(M)

(2, 3)

In [82]:
M.shape

(2, 3)

In [86]:
print(M.shape)
print(M.ndim)

(3, 3)
2


In [87]:
M.dtype

dtype('int64')

In [88]:
M = M.astype(np.float32)
print(M)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [98]:
np.array([[1,2,3],[4,5,6],[7,8]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [97]:
print(M)
print(M[1,2])
print(M[:,1])
print(M[2,:])
print(M[:2,:2])
print(M[[0,2],[1,2]])

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
6.0
[2. 5. 8.]
[7. 8. 9.]
[[1. 2.]
 [4. 5.]]
[2. 9.]


In [99]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [101]:
N = np.ones_like(M)

In [102]:
N = N*2
N

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)

In [105]:
N**2

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]], dtype=float32)

In [104]:
print(M+N)
print(M*N)

[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [110]:
print(M)
print(np.mean(M))
print(np.mean(M,axis=0))
print(np.mean(M,axis=1))
print(M.mean())

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
5.0
[4. 5. 6.]
[2. 5. 8.]
5.0


In [113]:
print(M.std())
print(-M)
print(np.abs(-M))
print(np.sum(M))

2.5819888
[[-1. -2. -3.]
 [-4. -5. -6.]
 [-7. -8. -9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
45.0


In [142]:
np.random.seed(0)
X = np.random.randn(3)
print(np.linalg.norm(X))


2.0566804594427484


In [143]:
np.dot(M,X)

array([ 5.50058072, 14.92942333, 24.35826595])

In [147]:
print(M.shape)
print(X.shape)
print(X)

(3, 3)
(3,)
[1.76405235 0.40015721 0.97873798]


In [149]:
np.dot(M,N)

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]], dtype=float32)

In [144]:
M @ X

array([ 5.50058072, 14.92942333, 24.35826595])

In [151]:
M.T @ N

array([[24., 24., 24.],
       [30., 30., 30.],
       [36., 36., 36.]], dtype=float32)

# Declaring functions

In [153]:
def my_fct(x,y): 
    z = x+y 
    return z

In [154]:
my_fct("a","b")

'ab'

In [155]:
my_fct(1,2)

3

In [156]:
my_fct(M,N)

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)

In [159]:
def fct(x): 
    return x+1, x-1
fct(1)

(2, 0)

In [161]:
tpl = fct(1)
print(tpl)
a,b = fct(1)
print(a,b)

(2, 0)
2 0


In [166]:
def fct(x,y=1,z=0):
    return x+y+z

In [167]:
my_fct(2)

TypeError: my_fct() missing 1 required positional argument: 'y'

In [168]:
fct(2)

3

In [169]:
fct(1,z=3)

5

In [170]:
fct(1,2,3)

6

In [171]:
fct(x=1,2,3)

SyntaxError: positional argument follows keyword argument (2762991000.py, line 1)

In [176]:
def label_fct(id:int,filename:str,format:str="csv")->str: 
    """ Defined filename
    Args:
        id (int): experiment
        filename (str): experiment name
        format (str, optional): result format. Defaults to "csv".

    Returns:
        str: filename
    """
    return f"{filename}_{id}."+format

In [177]:
label_fct(1,"first_exp")

'first_exp_1.csv'

In [181]:
pi = np.pi

print(pi)

print(f"{pi:.2f}")

3.141592653589793
3.14


In [183]:
x = 1/3
print(x)

0.3333333333333333


In [188]:
# question 8 

M = np.random.randn(10,10)
M[M<0] =0
M

array([[0.35629282, 0.        , 0.35548179, 0.81451982, 0.05892559,
        0.        , 0.        , 0.        , 0.80029795, 0.        ],
       [0.        , 1.73272119, 0.68450111, 0.370825  , 0.14206181,
        1.51999486, 1.71958931, 0.92950511, 0.58222459, 0.        ],
       [0.12372191, 0.        , 0.09395323, 0.94304609, 0.        ,
        0.        , 0.26990435, 0.        , 0.        , 0.86896349],
       [0.27687191, 0.        , 0.3148172 , 0.82158571, 0.00529265,
        0.8005648 , 0.07826018, 0.        , 0.        , 0.        ],
       [0.19429294, 0.87583276, 0.        , 0.45741561, 0.        ,
        0.        , 0.        , 0.        , 0.82024784, 0.46313033],
       [0.27909576, 0.33890413, 2.02104356, 0.        , 0.        ,
        0.1993002 , 0.        , 0.        , 0.        , 0.        ],
       [0.18133843, 0.        , 2.41245368, 0.        , 0.        ,
        0.        , 0.25148442, 0.        , 0.        , 0.        ],
       [0.        , 1.73887268, 0.9943943

In [190]:
M[(M<1)*(M>-1)] = 0
M

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.73272119, 0.        , 0.        , 0.        ,
        1.51999486, 1.71958931, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.02104356, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.41245368, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.73887268, 0.       

In [1]:
#generate a 5x5 matrix and replace the values in the 2nd column by 0
M = np.random.randn(5,5)
M[:,1] = 0
M

NameError: name 'np' is not defined